Repository NbcampUnreal/3rd_4th-Team16-CH4-Project, pull requests merged in 2025-09, with the labels that each got.

#17 [FIX] 로그인 저장 로직 수정
  OnlyOne/Source/OnlyOne/Private/Controllers/POMainMenuPlayerController.cpp
  OnlyOne/Source/OnlyOne/Private/Controllers/POServerLobbyPlayerController.cpp
  OnlyOne/Source/OnlyOne/Private/Game/POLobbyPlayerState.cpp
  OnlyOne/Source/OnlyOne/Public/Controllers/POServerLobbyPlayerController.h
  OnlyOne/Source/OnlyOne/Public/Game/POLobbyPlayerState.h
Labels: feature, gamemode

#19 Add character attack and synchronization improvements
  OnlyOne/Config/DefaultEngine.ini
  OnlyOne/Content/Assets/Mixamo/Cross_Punch.uasset
  OnlyOne/Content/Assets/Mixamo/TPose/Beta_HighLimbsGeoSG3.uasset
  OnlyOne/Content/Assets/Mixamo/TPose/Beta_Joints_MAT1.uasset
  OnlyOne/Content/Assets/Mixamo/TPose/X_Bot.uasset
  OnlyOne/Content/Assets/Mixamo/TPose/X_Bot_Anim.uasset
  OnlyOne/Content/Assets/Mixamo/TPose/X_Bot_PhysicsAsset.uasset
  OnlyOne/Content/Assets/Mixamo/TPose/X_Bot_Skeleton.uasset
  OnlyOne/Content/Character/Player/Animation/ABP_Player.uasset
  OnlyOne/Content/Character/Player/Animation/Attack/Cross_Punch.uasset
  OnlyOne/Content/Character/Player/Animation/Montages/AM_Player_Punch.uasset
  OnlyOne/Content/Character/Player/BP_POPlayerController.uasset
  OnlyOne/Content/Character/Player/BP_Player_Chacter.uasset
  OnlyOne/Content/Character/Player/DA_Player_InputData.uasset
  OnlyOne/Content/Character/Player/DA_Player_Startup_Data.uasset
  OnlyOne/Content/Character/Player/GAS/GameplayAbility/GA_Player_Attack.uasset
  OnlyOne/Content/Character/Player/GAS/GameplayEffect/GE_Damage_Calculation.uasset
  OnlyOne/Content/Character/Player/Input/Actions/IA_Player_Attack.uasset
  OnlyOne/Content/Character/Player/Input/IMC_Player_Default.uasset
  OnlyOne/Content/Character/Player/Mannequins/Meshes/SKM_Quinn.uasset
  OnlyOne/Content/Character/Player/Mannequins/Meshes/SK_Mannequin.uasset
  OnlyOne/Content/GameMode/BP_Test_GameMode.uasset
  OnlyOne/Content/Levels/FeatureTest.umap
  OnlyOne/Content/Shared/GameplayEffect/GE_Shared_DealDamage.uasset
  OnlyOne/Source/OnlyOne/Private/Characters/POCharacterBase.cpp
  OnlyOne/Source/OnlyOne/Private/Characters/POPlayerCharacter.cpp
  OnlyOne/Source/OnlyOne/Private/Components/Combat/PawnCombatComponent.cpp
  OnlyOne/Source/OnlyOne/Private/Components/Combat/PlayerCombatComponent.cpp
  OnlyOne/Source/OnlyOne/Private/Controllers/PONPCController.cpp
  OnlyOne/Source/OnlyOne/Private/Controllers/POPlayerController.cpp
  OnlyOne/Source/OnlyOne/Private/Game/POGameMode.cpp
  OnlyOne/Source/OnlyOne/Private/GameAbilitySystem/Abilities/POGameplayAbility.cpp
  OnlyOne/Source/OnlyOne/Private/GameAbilitySystem/Abilities/Player/POGameplayAbility_Attack.cpp
  OnlyOne/Source/OnlyOne/Private/GameAbilitySystem/Calculation/POGECalculation_DamageTaken.cpp
  OnlyOne/Source/OnlyOne/Private/GameAbilitySystem/POAttributeSet.cpp
  OnlyOne/Source/OnlyOne/Private/Notifies/AN_ToggleCollision.cpp
  OnlyOne/Source/OnlyOne/Private/POFunctionLibrary.cpp
  OnlyOne/Source/OnlyOne/Private/POGameplayTags.cpp
  OnlyOne/Source/OnlyOne/Private/POTypes/POEnumTypes.cpp
  OnlyOne/Source/OnlyOne/Public/Characters/POCharacterBase.h
  OnlyOne/Source/OnlyOne/Public/Characters/POPlayerCharacter.h
  OnlyOne/Source/OnlyOne/Public/Components/Combat/PawnCombatComponent.h
  OnlyOne/Source/OnlyOne/Public/Components/Combat/PlayerCombatComponent.h
  OnlyOne/Source/OnlyOne/Public/Components/Input/POInputComponent.h
  OnlyOne/Source/OnlyOne/Public/Controllers/POCharacterControllerBase.h
  OnlyOne/Source/OnlyOne/Public/Controllers/PONPCController.h
  OnlyOne/Source/OnlyOne/Public/Controllers/POPlayerController.h
  OnlyOne/Source/OnlyOne/Public/Game/POGameMode.h
  OnlyOne/Source/OnlyOne/Public/GameAbilitySystem/Abilities/POGameplayAbility.h
  OnlyOne/Source/OnlyOne/Public/GameAbilitySystem/Abilities/Player/POGameplayAbility_Attack.h
  OnlyOne/Source/OnlyOne/Public/Notifies/AN_ToggleCollision.h
  OnlyOne/Source/OnlyOne/Public/POFunctionLibrary.h
  OnlyOne/Source/OnlyOne/Public/POGameplayTags.h
  OnlyOne/Source/OnlyOne/Public/POTypes/POEnumTypes.h
Labels: feature, Character

#20 [Add] 테스트용 Listen Server 환경 구현
  OnlyOne/Content/Blueprints/MainMenu/BP_PlayerController_MainMenu.uasset
  OnlyOne/Content/Levels/L_MainMenu.umap
  OnlyOne/Content/ServerLobby/Blueprints/BP_ServerLobbyPlayerController.uasset
  OnlyOne/Content/UI/WBP_HostServer.uasset
  OnlyOne/Content/UI/WBP_MainMenu.uasset
  OnlyOne/Source/OnlyOne/Private/Controllers/POMainMenuPlayerController.cpp
  OnlyOne/Source/OnlyOne/Private/Controllers/POServerLobbyPlayerController.cpp
  OnlyOne/Source/OnlyOne/Private/Game/POLobbyPlayerState.cpp
  OnlyOne/Source/OnlyOne/Private/UI/MainMenu/POHostServerWidget.cpp
  OnlyOne/Source/OnlyOne/Private/UI/MainMenu/POMainMenuWidget.cpp
  OnlyOne/Source/OnlyOne/Public/Controllers/POMainMenuPlayerController.h
  OnlyOne/Source/OnlyOne/Public/UI/MainMenu/POHostServerWidget.h
  OnlyOne/Source/OnlyOne/Public/UI/MainMenu/POMainMenuWidget.h
Labels: feature, refactor, UI

#27 [ADD] 로비 게임시작 조건 구현
  OnlyOne/Source/OnlyOne/Private/Controllers/POMainMenuPlayerController.cpp
  OnlyOne/Source/OnlyOne/Private/Game/POLobbyGameMode.cpp
  OnlyOne/Source/OnlyOne/Private/Game/POLobbyGameState.cpp
  OnlyOne/Source/OnlyOne/Private/Game/POLobbyPlayerState.cpp
  OnlyOne/Source/OnlyOne/Public/Game/POGameInstance.h
  OnlyOne/Source/OnlyOne/Public/Game/POLobbyGameMode.h
  OnlyOne/Source/OnlyOne/Public/Game/POLobbyGameState.h
  OnlyOne/Source/OnlyOne/Public/Game/POLobbyPlayerState.h
Labels: feature, gamemode

#24 [ADD] UI Stacking 구현
  OnlyOne/Content/UI/MainMenu/WBP_JoinServer.uasset
  OnlyOne/Source/OnlyOne/Private/Controllers/Components/POUIStackingComonent.cpp
  OnlyOne/Source/OnlyOne/Private/Controllers/Interfaces/POUIStackingInterface.cpp
  OnlyOne/Source/OnlyOne/Private/Controllers/POMainMenuPlayerController.cpp
  OnlyOne/Source/OnlyOne/Private/UI/Common/POBaseWindow.cpp
  OnlyOne/Source/OnlyOne/Private/UI/MainMenu/POHostServerWidget.cpp
  OnlyOne/Source/OnlyOne/Private/UI/MainMenu/POJoinServerWidget.cpp
  OnlyOne/Source/OnlyOne/Public/Controllers/Components/POUIStackingComonent.h
  OnlyOne/Source/OnlyOne/Public/Controllers/Interfaces/POUIStackingInterface.h
  OnlyOne/Source/OnlyOne/Public/Controllers/POMainMenuPlayerController.h
Labels: feature, refactor, UI

#30 [Add] NPC GA_Death 추가 및 Death 몽타주 수정 + NPC 테스트레벨 추가
  OnlyOne/Content/Character/NPC/AI/BT_NPC.uasset
  OnlyOne/Content/Character/NPC/DA_NPC_Startup.uasset
  OnlyOne/Content/Character/NPC/GA/GA_NPC_Death.uasset
  OnlyOne/Content/Character/Player/Animation/Montages/AM_Death.uasset
  OnlyOne/Content/Levels/NPC_Test_Level.umap
  OnlyOne/Source/OnlyOne/Private/Characters/PONPCCharacter.cpp
  OnlyOne/Source/OnlyOne/Private/GameAbilitySystem/Abilities/NPC/PONPCGameplayAbility_Death.cpp
  OnlyOne/Source/OnlyOne/Public/Characters/PONPCCharacter.h
  OnlyOne/Source/OnlyOne/Public/GameAbilitySystem/Abilities/NPC/PONPCGameplayAbility_Death.h
Labels: feature, AI

#36 [Add] AI 행동 트리 작업 노드 추가 BTT_SetRandomSpeed
  OnlyOne/Content/Character/NPC/AI/BT_NPC.uasset
  OnlyOne/Source/OnlyOne/Private/AI/Tasks/BTT_SetRandomSpeed.cpp
  OnlyOne/Source/OnlyOne/Public/AI/Tasks/BTT_SetRandomSpeed.h
Labels: feature, AI

#38 [ADD] Player 상태 리스트 UI 구현
  OnlyOne/Content/Levels/L_UITest.umap
  OnlyOne/Content/UI/PlayerStateList/BP_UITestPlayerController.uasset
  OnlyOne/Content/UI/PlayerStateList/BP_UITest_Gamemode.uasset
  OnlyOne/Content/UI/PlayerStateList/WBP_PlayerStateElement.uasset
  OnlyOne/Content/UI/PlayerStateList/WBP_PlayerStateList.uasset
  OnlyOne/Source/OnlyOne/Private/Controllers/POPlayerController.cpp
  OnlyOne/Source/OnlyOne/Private/Controllers/POUITestPlayerController.cpp
  OnlyOne/Source/OnlyOne/Private/UI/PlayerStateList/POPlayerStateElementWidget.cpp
  OnlyOne/Source/OnlyOne/Private/UI/PlayerStateList/POPlayerStateListWidget.cpp
  OnlyOne/Source/OnlyOne/Public/Controllers/POPlayerController.h
  OnlyOne/Source/OnlyOne/Public/Controllers/POUITestPlayerController.h
  OnlyOne/Source/OnlyOne/Public/UI/PlayerStateList/POPlayerStateElementWidget.h
  OnlyOne/Source/OnlyOne/Public/UI/PlayerStateList/POPlayerStateListWidget.h
Labels: feature, UI

#43 [ADD] PlayerState 초기화 및 상태 변경 델리게이트 브로드캐스트
  OnlyOne/Source/OnlyOne/Private/Game/POLobbyPlayerState.cpp
  OnlyOne/Source/OnlyOne/Private/Game/POStageGameMode.cpp
  OnlyOne/Source/OnlyOne/Public/Game/POLobbyPlayerState.h
Labels: feature, gamemode

#44 [ADD] Stage Timer 구현
  OnlyOne/Content/Levels/L_UITest.umap
  OnlyOne/Content/UI/PlayerStateList/BP_UITestPlayerController.uasset
  OnlyOne/Content/UI/StageTimer/WBP_StageTimer.uasset
  OnlyOne/Content/UI/WBP_HUD.uasset
  OnlyOne/Source/OnlyOne/Private/Controllers/Components/POUIStackingComonent.cpp
  OnlyOne/Source/OnlyOne/Private/Controllers/Components/POUIStackingComponent.cpp
  OnlyOne/Source/OnlyOne/Private/Controllers/POMainMenuPlayerController.cpp
  OnlyOne/Source/OnlyOne/Private/Controllers/POPlayerController.cpp
  OnlyOne/Source/OnlyOne/Private/Controllers/POUITestPlayerController.cpp
  OnlyOne/Source/OnlyOne/Private/UI/MainMenu/POHostServerWidget.cpp
  OnlyOne/Source/OnlyOne/Private/UI/MainMenu/POJoinServerWidget.cpp
  OnlyOne/Source/OnlyOne/Private/UI/StageTimer/POStageTimerWidget.cpp
  OnlyOne/Source/OnlyOne/Public/Controllers/Components/POUIStackingComponent.h
  OnlyOne/Source/OnlyOne/Public/Controllers/Interfaces/POUIStackingInterface.h
  OnlyOne/Source/OnlyOne/Public/Controllers/POMainMenuPlayerController.h
  OnlyOne/Source/OnlyOne/Public/Controllers/POPlayerController.h
  OnlyOne/Source/OnlyOne/Public/Controllers/POUITestPlayerController.h
  OnlyOne/Source/OnlyOne/Public/UI/StageTimer/POStageTimerWidget.h
Labels: feature, UI

#49 bug: 사망 애니메이션 동기화 문제 수정
  OnlyOne/Content/Character/Player/Animation/Montages/AM_Death.uasset
  OnlyOne/Source/OnlyOne/Private/Characters/POPlayerCharacter.cpp
  OnlyOne/Source/OnlyOne/Private/GameAbilitySystem/Abilities/Player/POPlayerGameplayAbility_Death.cpp
  OnlyOne/Source/OnlyOne/Public/Characters/POPlayerCharacter.h
  OnlyOne/Source/OnlyOne/Public/GameAbilitySystem/Abilities/Player/POPlayerGameplayAbility_Death.h
Labels: bugfix, Character
